# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  # who-to-greet:  # id of input
  #   description: 'Who to greet'
  #   required: true
  #   default: 'World'
  fruit: 
    description: Name of fruit to mask
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: docker://mithungudipati/argocd:latest
  # args:
  #   - ${{ inputs.who-to-greet }}
